_schema: _schema
paths:
  uploads: static/uploads
  static: static
collections_config:
  content:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
  posts:
    path: /content/posts
    glob:
    name:
    singular_name:
    icon: notes
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: ''
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
      date:
        type: date
        options:
          timezone:
          empty_type:
        instance_value: NOW
        cascade: true
      blogs:
        type: multiselect
        options:
          allow_create:
          empty_type: array
          values:
            - Good News
            - Politik
            - Reflexionen
            - Klima
            - Tiefsee
            - Überfischung
            - Forschung
            - Kultur
            - Was tun
          value_key:
          preview:
          picker_preview:
          view:
          picker_view:
        cascade: true
      image:
        type: image
        cascade: true
      image_caption:
        type: text
        options:
          empty_type:
        cascade: true
      author:
        type: select
        options:
          allow_create: true
          allow_empty: false
          values:
            - DEEPWAVE
          value_key:
          preview:
          picker_preview:
          view:
          picker_view:
        cascade: true
      source:
        type: text
        cascade: true
    _select_data:
    _structures:
    add_options: []
    create:
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    new_preview_url:
    schema_key: blog_template
    schemas:
      blog_post:
        path: .cloudcannon/schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        icon: post_add
  timeline:
    path: /content/ueber uns/wer wir sind
    glob:
    name:
    singular_name:
    icon: notes
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: ''
    preview:
    sort:
      key: date
      order: desc
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
      date:
        type: date
        options:
          timezone:
          empty_type:
        instance_value: NOW
        cascade: true
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_select_data:
  Categories: []
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: Europe/London
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
