baseURL = "http://www.deepwave.org/"
languageCode = "en-us"
title = "Wir gebem dem Meer eine Stimme"
theme = "dwtheme"



[taxonomies]
  category = "blogs"
  author = "author"
[permalinks]
  posts = "/:filename/"

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[params]
  defaultImage = "https://res.cloudinary.com/deepwave-org/image/upload/v1747267232/deepwave.org/Ice_Background_Philipp_Griess.jpg"
  logo = "https://res.cloudinary.com/deepwave-org/image/upload/v1747346944/deepwave.org/deepwave_logo_de_4c_hor_SVG_ein_Pfad_s46prq.svg"

[params.cld]

url = "https://res.cloudinary.com/deepwave-org/"
transform = "c_fill,w_auto,g_auto,q_auto,dpr_auto/f_auto"