baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "dwtheme"

[taxonomies]
  category = "blogs"
[permalinks]
  posts = "/:filename/"

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[params]
  footericon = "/images/onno-gross.jpg"
  footertext = "Jeden Tag, mit jedem Quadratmeter Schutzgebiet, jedem Verzicht auf Fisch und jeder Vermeidung von Plastikmüll können wir die Ozeane und unseren Planeten bewahren."
  footerlogo = "/images/deepwave-logo.png"
  footerimg = "/images/ocean-footer.jpg"
  newstitle = "Interessiert an Neuigkeiten zum Meeresschutz?"
  newsundertitle = "Dann halten wir dich mit unserem Newsletter auf dem Laufenden."
  footernewsone = "/images/newsletter-preview-1.jpg"
  footernewstwo = "/images/newsletter-preview-2.jpg"

[params.cld]

url = "https://res.cloudinary.com/deepwave-org/"
transform = "c_fill,w_auto,g_auto,q_auto,dpr_auto/f_auto"